package calc.entity.calc.enums;

public enum DefMethodLoss {
	DML_BY_VOLUME_ON_BOTH_SIDES,
	DML_WN_PLUS_WCD,
	DML_AVG_FACTOR,
	DML_MD_ELSE_WN_PLUA_WCD,
	DML_MD_ELSE_AVG_FACTOR,
	DML_LOSSES_NOT_REQUIRED
}